image: node:10

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - audit

# test:
#   stage: test
#   except:
#     - schedules
#   script:
#     - yarn install --pure-lockfile --cache-folder .yarn
#     - yarn test:ci
#   coverage: '/^Statements\s*:\s*([^%]+)/'

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit
